### ISSUE TITLE
get_scripts.R not able to open repository

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/Regional_SDM#20]
This error keeps popping up:

> Error in validObject(.Object) : 
>   invalid class “git_repository” object: Unable to open repository at 'path'

Upgraded R, packages, etc and the same error persists.

**Comment by dnbucklin** [comment]
I think this is from the `git2r::repository` function. It would happen if you already have a folder named `Regional_SDM_[datestamp]` in the folder you specify for `loc_scripts`, but that folder is not initialized as a git repository (just a regular folder).

You could either rename/move that existing `Regional_SDM_[datestamp]` folder, or just specify a new empty folder for `loc_scripts`.

**Comment by dnbucklin** [comment]
Ok, my fix for this (b010a10d62cd6298aeca38981963f6e109a12779) was just to ignore these non-git folders. So now when you run `helper/get_scripts.R`, and the latest `Regional_SDM_YYYY_MM_DD` folder it finds is not a git repo, it will ignore it and create a new git repo with the current date, and return this new folder path to move forward with as `loc_scripts`.

Also note that I changed the path to `get_scripts` in `user_run_SDM` to it's path in the git repo (in the `helper` sub-folder).
